services:
  auth-server:
    build:
      context: ../auth-service
      dockerfile: ./build/auth/Dockerfile
    container_name: demo-auth-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${AUTH_SERVER_CONTAINER_PORT}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    ports:
      - "${AUTH_SERVER_HOST_PORT}:${AUTH_SERVER_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:${AUTH_SERVER_CONTAINER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  user-server:
    build:
      context: ../user-service
      dockerfile: ./build/user/Dockerfile
    container_name: demo-user-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${USER_SERVER_CONTAINER_PORT}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_HOST=${USER_DB_HOST}
      - DB_PORT=${USER_DB_CONTAINER_PORT}
      - DB_NAME=${USER_DB_NAME}
      - AUTH_SERVICE_HOST=${AUTH_SERVER_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVER_CONTAINER_PORT}
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - "${USER_SERVER_HOST_PORT}:${USER_SERVER_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:${USER_SERVER_CONTAINER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  user-db:
    image: postgres:17
    container_name: demo-user-db
    restart: always
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "${USER_DB_HOST_PORT}:${USER_DB_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - demo-user-db-data:/var/lib/postgresql/data

  auth-grpc-gateway:
    build:
      context: ../auth-service
      dockerfile: ./build/gateway/Dockerfile
    container_name: demo-auth-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - GRPC_GATEWAY_PORT=${AUTH_GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${AUTH_SERVER_HOST}
      - SERVER_PORT=${AUTH_SERVER_CONTAINER_PORT}
    ports:
      - "${AUTH_GRPC_GATEWAY_HOST_PORT}:${AUTH_GRPC_GATEWAY_CONTAINER_PORT}"

  user-grpc-gateway:
    build:
      context: ../user-service
      dockerfile: ./build/gateway/Dockerfile
    container_name: demo-user-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - GRPC_GATEWAY_PORT=${USER_GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${USER_SERVER_HOST}
      - SERVER_PORT=${USER_SERVER_CONTAINER_PORT}
    ports:
      - "${USER_GRPC_GATEWAY_HOST_PORT}:${USER_GRPC_GATEWAY_CONTAINER_PORT}"

volumes:
  demo-user-db-data: