services:
  auth-server:
    build:
      context: ../auth
      dockerfile: ./build/auth/Dockerfile
    container_name: auth-server
    restart: always
    environment:
      - PORT=${AUTH_SERVER_PORT}
      - KEYCLOAK_SERVER_BASE_URL=${KEYCLOAK_SERVER_BASE_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_CLIENT_REDIRECT_URI=${KEYCLOAK_CLIENT_REDIRECT_URI}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    ports:
      - "${AUTH_SERVER_EXTERNAL_PORT}:${AUTH_SERVER_PORT}"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:${AUTH_SERVER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  keycloak-server:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak-server
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: "http://localhost:${KEYCLOAK_SERVER_EXTERNAL_PORT}"
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-db:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_NAME}
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      keycloak-db:
        condition: service_healthy
    command: start-dev
    ports:
      - "${KEYCLOAK_SERVER_EXTERNAL_PORT}:${KEYCLOAK_SERVER_PORT}"
    volumes:
      - ../auth/keycloak/themes:/opt/keycloak/themes

  keycloak-db:
    image: mysql:8.0
    container_name: keycloak-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_NAME}
      MYSQL_USER: ${KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "${KEYCLOAK_DB_EXTERNAL_PORT}:${KEYCLOAK_DB_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${KEYCLOAK_DB_USER}", "-p${KEYCLOAK_DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - keycloak-db-data:/var/lib/mysql

  user-server:
    build:
      context: ../user
      dockerfile: ./build/user/Dockerfile
    container_name: user-server
    restart: always
    environment:
      - PORT=${USER_SERVER_PORT}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_HOST=${USER_DB_HOST}
      - DB_PORT=${USER_DB_PORT}
      - DB_NAME=${USER_DB_NAME}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVER_EXTERNAL_PORT}
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - "${USER_SERVER_EXTERNAL_PORT}:${USER_SERVER_PORT}"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:${USER_SERVER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "${USER_DB_EXTERNAL_PORT}:${USER_DB_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${USER_DB_USER}", "-p${USER_DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - user-db-data:/var/lib/mysql

volumes:
  keycloak-db-data:
  user-db-data:

networks:
  shared: